### ISSUE TITLE
Action after "Validate" does not redirect automatically

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#120]
Sorry.. not sure how to term it correctly, but i noticed today that after clicking "OK" when making an action on "Validate", the dialogue box does not go away/ the dashboard does not automatically redirect to show the action made; rather, a hard refresh must be made in order to see the "saved" action:

https://github.com/mlab817/pips/assets/143272008/433d7b51-fb02-4075-ae64-e95a45919a15

**Comment by mlab817** [comment]
Thanks for reporting this. Will fix asap.

Code in question: [lib/presentation/widgets/reviewer_view.dart](https://github.com/mlab817/xpips/blob/0455a664b928ca62f25d65f0c8892e582d4d61d4/lib/presentation/widgets/reviewer_view.dart)

**Comment by mlab817** [comment]
Upon checking, the problem seems to be that there are two running instance of horizon for notification queues which is throwing the error. Anyway, it's a bit technical but has nothing to do with the code.
