### ISSUE TITLE
Request for verification on possible sudden loss of some indicators in expected deliverables

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#131]
Re: PAP on "Abaca Development Program",
I remember seeing a few weeks ago in their list of Expected Outputs/ Deliverables an indicator concerning a facility *specific to * Catanduanes. This is in keeping with the sub-project under this same PAP concerning establishment of production facility in Catanduanes as listed in their Description.

but looking at the list right now, said indicator is missing:

![image](https://github.com/mlab817/pips/assets/143272008/d9c6f065-3dc7-4353-a608-6fef361b4962)

Per PhilFIDA IP Coordinator, she also concurred, stating that some indicators they have already encoded for this PAP are now missing.

May we seek assistance if you can backtrack or trace re: "missing" indicators? at least the indicators on "Establishment of Catanduanes Tissue Culture Laboratory" and something about "Abaca Genebank "... there are more but those are the ones i distinctly remember.. thanks

**Comment by mlab817** [comment]
Unfortunately, the system permanently deletes the project indicators so I can't trace them if they are deleted. :(
