### ISSUE TITLE
Problem with Approval and Disapproval feature in DA PIPS

### ISSUE THREAD

**Issue by AlexEstoesta** [dapmsipd/pips#132]
Upon perusing the Approve option in the DA PIPS, an error occurred and the PAP was labeled as disapproved. 

Upon consultation with developer, and using the option anew, it marked successfully updated status per dialogue box. However, the status of disapproval is still labeled to the PAP even though the page has been reloaded and the user logging in anew

**Desktop:**
 - OS: MS Windows
 - Browser: Chrome
 - Version :118.0.5993.72 (Official Build) (64-bit)

**Comment by mlab817** [comment]
Please include error message next time for easier review and validation of error.
