### ISSUE TITLE
Request to sync History log with the "Latest Activity" data

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#136]
Example for PAP on NOAP, on my reviewer account, the "Latest Activity" specifies me as the last user to make any changes on the PAP (last change made yesterday, Oct 25):
![image](https://github.com/mlab817/pips/assets/143272008/9ca1d3a7-836b-40ae-a098-0014653dcdeb)

However, said PAP is being updated as of Oct 26 by the IP encoder (Lois Daniel Hacela), as indicated in the PAP's history log:

![image](https://github.com/mlab817/pips/assets/143272008/3f8cb1ab-8685-43f9-a345-7930b32914b6)

**Comment by mlab817** [comment]
Ok, the problem was I was using the wrong syntax to trigger logging. I used event() instead of log().
