### ISSUE TITLE
Downloaded project file (excel) cannot be opened in Excel

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#138]
https://github.com/mlab817/pips/assets/143272008/482fbfec-8d14-4f3c-8872-c9cb37cf41e4

**Comment by mlab817** [comment]
Thanks for calling my attention as I rarely login to an encoder account. The encoder account will also receive an email for their downloaded file but I forgot to update the logic to inform the user instead of download the excel file in their browser.
