### ISSUE TITLE
Changes in the Investment Cost per Province does not reflect right away unless refreshed.

### ISSUE THREAD

**Issue by jamieangeles** [dapmsipd/pips#143]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mlab817** [comment]
Does this include all operations:

- add new provincial breakdown?
- edit
- delete

?

**Comment by jamieangeles** [comment]
Add new provincial breakdown - Yes. Walang nagrereflect unless refreshed.
Edit - Yung total lang ang nagrereflect agad (unless refreshed)
Delete - Yung total lang ang nadedelete (unless refreshed)

**Comment by jamieangeles** [comment]
![Screenshot 2023-11-08 173947](https://github.com/mlab817/pips/assets/143672911/53cb8e4c-2312-4ec8-9288-c459c75c287f)

This appears when deleting entries. The deleted PAP still appears even after clicking the confirm button. Still needs to be refreshed.
