### ISSUE TITLE
Expected Outputs/Deliverables. 1) Returns to homepage when deleting indicators (see screenshot); 2) New inputs and edits do not reflect right away unless refreshed

### ISSUE THREAD

**Issue by jamieangeles** [dapmsipd/pips#145]
![Homepage](https://github.com/mlab817/pips/assets/143672911/98ee8931-f5d5-44d4-925f-d5bcdf8c4a8e)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mtayco** [comment]
Same issue with mine. Edit form does not automatically refresh/ show the revision after clicking "save". User has to do a hard refresh and go back to the dashboard


https://github.com/mlab817/pips/assets/143272008/024280ab-5eda-4874-9700-6d2837de08ae

**Comment by mlab817** [comment]
Thanks for reporting this.

The reason this was happening was because of the search functionality added that saves the data in another variable.

Anyway, this is corrected.

The same is true for the provincial investment field. I'll try to fix it asap.
