### ISSUE TITLE
Suggestion to require target date of ICC/ NEDA Board submission for CIPs

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#146]
Currently in PIPS, for CIPs, regardless of approval status, we only require the date "as of"... 

![image](https://github.com/mlab817/pips/assets/143272008/81e2a7dd-d958-40a8-b121-2237c968ce9f)

but in the PIPOL, certain dates will be required depending on the Level of CIP approval (such as the target date of submission for those that will be classified as yet to be submitted):

![image](https://github.com/mlab817/pips/assets/143272008/b3932cbe-168f-4ee8-ae8f-06d4e093db86)

If possible, that PIPS to mirror these requirements depending on the type of approval selected?

![image](https://github.com/mlab817/pips/assets/143272008/4a56849e-5554-4b14-bdb7-68a6c31ff8f2)

![image](https://github.com/mlab817/pips/assets/143272008/349bc12e-2641-4ff4-ad08-fe464878a21d)

![image](https://github.com/mlab817/pips/assets/143272008/a5b052c0-b49b-4529-88f2-e442cb38e064)

![image](https://github.com/mlab817/pips/assets/143272008/35b2f98a-164b-4c23-b079-51b9525b8b6f)

**Comment by mlab817** [comment]
Only one instance of the date is saved so I just used a single date field to represent that. so whatever as_of contains, that should mean the relevant date. what i can do is replace the label of the date field depending on the status selected. i'll try that.
