### ISSUE TITLE
PDP Chapter: The Main PDP Chapter (which is not checked in the Other PDP Chapter/s dropdown) automatically appears in the Other PDP Chapters. Not all PAPs have this issue.

### ISSUE THREAD

**Issue by jamieangeles** [dapmsipd/pips#147]
**Describe the bug**
![Screenshot 2023-11-08 101617](https://github.com/mlab817/pips/assets/143672911/869b6fac-efa6-455b-aedd-c968748a8a57)

**Comment by mlab817** [comment]
This was probably caused by last year's updating that required users to reselect the main pdp chapter in the other pdp chapter.
