### ISSUE TITLE
New archive creation before start of annual updating

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#203]
Ensure that before every start of actual updating period, a new archive of the prior year's updating has been created, viewable, uneditable, and non-*deletable*.

At the same time, "duplicates" of the prior year's PAPs have been readily loaded in the "Submitted" module and opened for editing once the editing period has commenced.

**Comment by clorae** [comment]
Functional Implications:
Once the "Encoding Start," "Encoding Deadline," and "Updating Period" parameters are configured in the PIPS Admin App Settings, the system will exhibit the following behaviors in PIPS:

Encoder's Perspective
Upon editing the above parameters, the PAP button transforms into an "Update" button.

Archive Copy
Simultaneously, an archival copy of the PAP is created, preserving the configuration before the update. This archived version is viewable for reference.

Updated PAP Copy
Additionally, a copy of the PAP is generated, reflecting the new encoding parameters set in the "Updating Period" of the App Settings.

Refer to the attached images for a step-by-step visual guide on how to set the "Encoding Start," "Encoding Deadline," and "Updating Period" parameters in the App Settings.
![image](https://github.com/dapmsipd/pips/assets/6055561/7cfebf05-9c9b-4b8a-8130-ab079cb828de)

Once you clicked "Edit" ensure that all checkboxes are NOT MARKED. Only the three (3) parameters should be filled. Then click Submit.
![image](https://github.com/dapmsipd/pips/assets/6055561/b6f6efff-1267-45ca-b714-dfaf3f10a842)

This will be updated on the PIPS Documentation for future reference.
