### ISSUE TITLE
DA PIPS data on provincial breakdown is no longer available

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#204]
Just noticed today:
All PAPs in DA-PIPS that have provincial investment targets no longer have the data on provincial breakdown.
sample for National Rice Program: below is the current info in PIPS:

![image](https://github.com/dapmsipd/pips/assets/143272008/cf18b689-f9ff-4c4b-b9ea-b309ae6dd22f)

Per DA-PIPS data exported last Jan 4: there are provincial breakdowns for NRP:
![image](https://github.com/dapmsipd/pips/assets/143272008/7f2e876e-974e-4002-bbde-08a986fdcedc)

Tried to export DA PIPS data today, and so far the provincial data are there. Thus, the concern is that in DA PIPS, the provincial table shows "no items found"

![image](https://github.com/dapmsipd/pips/assets/143272008/850e83be-c596-4d51-848c-c445b37619be)

**Comment by clorae** [comment]
Working on it on this bug.  I'll update as soon as it is resolved. Thank you, Ma'am

**Comment by clorae** [comment]
While I am actively working on resolving the bug, here's a temporary workaround to address the issue. 

https://github.com/dapmsipd/pips/assets/6055561/a9826c32-7867-474c-bbc2-1976040279ce
