### ISSUE TITLE
Print function not working for certain PAP

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#32]
issue from PhilFIDA, PAP on "Other fibercrops..."
 Print function shows 404 error. Print function for other PAPs is working

https://github.com/mlab817/pips/assets/143272008/b14af542-4f41-4128-9365-42bd55f63ff4

**Comment by mlab817** [comment]
Tokens can be (re)generated by clicking on the Share button.

I think that the system does not generate access_token for updated PAPs. Will fix.
