### ISSUE TITLE
For Reviewer accounts, allow function for Print/ download of List of PAPs

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#37]
![Reviewer Print function](https://github.com/mlab817/pips/assets/143272008/9fbaf11d-76db-4cf2-b57b-3a2f947d807e)

Also, if the downloaded list from Reviewer accounts can have the usual information (PIPOL code, title, Program/ Project, Office, Description, and so on ). This is to aid at least the Reviewers (including PDS, SPCMAD, and BAFE) to be able to quickly find , or sort the PAPs. Also, if they wish to have an excel list of PAPs that they have reviewed, for documentation.

![image](https://github.com/mlab817/pips/assets/143272008/dcb3c95f-0a9d-40a0-8e0d-61795a54678d)

**Comment by mtayco** [comment]
If possible also please to include in the Reviewer dashboard (perhaps next to the Period column), the PIPOL CODE. This is for reviewers to be able to quickly see if there are new entries being created that actually refer to existing PAPs.

![373466574_852863723214126_4929530883102593843_n](https://github.com/mlab817/pips/assets/143272008/37d4fd10-e54f-46fb-8a17-502ac994038b)

**Comment by mlab817** [comment]
Instead of the PIPOL Code, I implemented this with a `NEW` badge in the title of the PAP instead.
