### ISSUE TITLE
(Possibly an isolated case) PAP on Cotton Development Project does not show Investment Cost per province

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#43]
PhilFIDA encoder has sent the following screenshot showing the missing table on Investment Cost per Province, despite having selected the provinces in the Spatial Coverage (also, despite repeated page refresh):
![373473881_1285094575478417_6988769034612634363_n](https://github.com/mlab817/pips/assets/143272008/74a05b01-3d71-4f36-94e8-36904f1a4778)

![373485876_255263857493077_5186550855579355731_n (9)](https://github.com/mlab817/pips/assets/143272008/9f1f96dd-27dd-4f52-9788-014ef8925292)

On my browser, the Provincial table can be seen:
![Screen Shot 2023-09-08 at 6 45 48 PM](https://github.com/mlab817/pips/assets/143272008/2afdb82b-c454-4bef-9bf9-bd024e216bcc)

have requested them to refresh again, as well as to log out and then back in. same issue occurs

**Comment by mlab817** [comment]
1. Use a different browser or clear cache.
2. Make sure they are reloading the browser, not the app (the reload button in app).

**Comment by mlab817** [comment]
I am closing this issue. Please refer to https://github.com/mlab817/pips/issues/44#issuecomment-1711669657 for the solution.
