### ISSUE TITLE
(Possibly an isolated case) PAP Profile summary does not show "Share" button

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#44]
Still from PhilFIDA encoder, the PAP Summary box (cotton development project) does not show the "Share" button. When they tried to get a PDF file using the Print, the 404 error shows

![373473963_313640794670310_4106993464372682414_n](https://github.com/mlab817/pips/assets/143272008/fed1bd18-f5fa-4e52-97e4-ec36e0b030bc)
![373482262_996042404986111_6608540258200852818_n](https://github.com/mlab817/pips/assets/143272008/19e6f69c-2fee-41da-a675-7b1d501f8bce)

**Comment by mlab817** [comment]
The website pips-demo-app.web.app is not kept updated. As the url suggests, that is the demo app for pips and is used for demo purposes only. I have already taken down this url. Please advise OU to use https://app.pips.da.gov.ph instead.
