### ISSUE TITLE
Print version does not capture all expected deliverables

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#48]
A PAP has listed many expected outputs:

![image](https://github.com/mlab817/pips/assets/143272008/f951dd03-2aed-4902-ab60-3fabca9a2a97)

But the PDF/ print version does list all:

![image](https://github.com/mlab817/pips/assets/143272008/0168989a-1e42-4d7c-adb6-6993c1d2cb08)

**Comment by mlab817** [comment]
got this thanks. this has something to do with not fitting the entire table in the previous page.
