### ISSUE TITLE
"Last update" is still not updating 

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#55]
Issue on PAP on "Other Fibercrops..." of PhilFIDA.
IP Encoder claims to have made numerous updates today, sept 13. but the "Last update" status still shows Sept 12. 

Log history accessed today (sept 13) through my reviewer account also only shows Sept 12 as the last movement

![image](https://github.com/mlab817/pips/assets/143272008/a8912a4d-1cac-4027-b413-9d7c286b412e)

**Comment by mlab817** [comment]
I am not sure what's happening with this PAP but I also noticed in the backend that other logs were not being retrieved and displayed in the frontend, including project_indicators and provincial_investments. For Provincial investments, unfortunately, I forgot to include them in the project logs so they will not reflect. As for the other items, I am not sure.

One way to debug this is to check right away if a change made was reflected in the history logs.
