### ISSUE TITLE
401 error in Print function

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#59]
PAP of BFAR on "Comprehensive 5 Year Modernization Plan of Bureau of Fisheries and Aquatic Resources Laboratories: Upgrading and Expansion of Laboratory Capacities and Services of BFAR Fisheries Laboratories and Accreditation with PNS ISO/IEC 17025:2017 in support to the Improvement of Production, Animal Health, Food Safety of Fish and Fishery Products", print button redirects to 401 error.

https://github.com/mlab817/pips/assets/143272008/2c5c1dd2-85d2-463b-b177-6c2f8f3e5cd9

the Share url works though. so. ive requested them for now to just use that

**Comment by mlab817** [comment]
For PAPs na duplicated, access token generation may error sometimes. Regenerating the access token with share should work.
