### ISSUE TITLE
Submitting/ Deleting comments redirects back to edit form

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#65]
Request that after submitting or deleting a comment, to remain on the comments list page, rather than be redirected to the edit form

https://github.com/mlab817/pips/assets/143272008/1a11e372-3bd9-40e1-ac10-13db4346da7c

**Comment by mlab817** [comment]
Fixed by https://github.com/mlab817/xpips/commit/eef15fffe553de195f5915e42fb719a43f57687b
