### ISSUE TITLE
Request for downloaded form for table on expected outputs

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#67]
For IPD staff who will transfer/ update info on PIPOL, some PAPs have numerous expected outputs/ indicators. Request to generate an excel form that will capture the Expected Outputs section for easier encoding to PIPOL.

The IPD reviewer accounts do not have a Print feature for assigned PAPs.

**Comment by mlab817** [comment]
> For IPD staff who will transfer/ update info on PIPOL, some PAPs have numerous expected outputs/ indicators. Request to generate an excel form that will capture the Expected Outputs section for easier encoding to PIPOL.

How would you like the download to be generated? I suggest that the downloaded data be in text form so the encoders can just copy-paste it to the expected outputs/deliverables field.

**Comment by mtayco** [comment]
Yes please. text form is fine. thanks
