### ISSUE TITLE
No "select all" button for Comments

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#73]
Request to bring back the check all/ select all button in the Comments page

![image](https://github.com/mlab817/pips/assets/143272008/927088af-a8a5-4056-a340-073f5b76d74b)

Also, what will happen if a comment is already submitted but it can still be activated or selected for "Submission"?

https://github.com/mlab817/pips/assets/143272008/98acc540-16b3-4ceb-a655-a496141a1eb6

**Comment by mlab817** [comment]
- I will review the "check all" function for the comments screen but the reason there was no check all button was that, there will be comments there that you should not have access like those added by other reviewers.
- as to resubmitting the comments, there's no bearing for that. it will just be submitted again.
