### ISSUE TITLE
Archived profile shows Zero annual investment targets

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#78]
Using the ipd_encoder1b account, in the Archive page, when viewing the PAP profile, the annual disaggregation of investment targets is zero

https://github.com/mlab817/pips/assets/143272008/6eebd59c-af3a-4672-82da-c81c1ca7a344

...need to be able to see the data submitted in preceding cycle

**Comment by mlab817** [comment]
This happened to the first PAPs that were duplicated and quite a lot were affected. I already have the code to fix this but i need to backup the database first. Thanks for calling my attention.

**Comment by mlab817** [comment]
this is done.
