### ISSUE TITLE
Downloaded masterfile ("project" xlsx file) to also reflect Reasons for exclusion

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#87]
Something like so... to inform the person who downloaded the file that certain PAPs were "recommended for exclusion" and why (and to allow sorting)

![image](https://github.com/mlab817/pips/assets/143272008/4acaf679-2701-47bc-9223-074fbc2dbe5f)

**Comment by mlab817** [comment]
can we like provided other relevant columns para di installment itech? Thanks.

**Comment by mtayco** [comment]
For now, the columns in the Reviewer dashboard are the only ones i can think of that should also be reflected in the print out...  (to include respective columns for  "reasons for ___" if results are negative) 

![image](https://github.com/mlab817/pips/assets/143272008/1e01e444-7831-483e-af1b-2ec94e5eaa7c)

so perhaps something like..
- Reasons for dropping
- Reasons for excluding
- Reasons for disapproval
